src/main/java/nl/haarlem/translations/zdstozgw/config/ModelMapperConfig.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/GeefZaakdocumentLezenReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/Replicator.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/client/ZDSClient.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsEdcLv01.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsParameters.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsScope.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsScopeGerelateerde.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsScopeHeeftRelevant.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsScopeObject.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsZaak.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsZaakDocument.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zgw/model/ZgwEnkelvoudigInformatieObject.java
=> Replicatie wat netter gemaakt

src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/Replicator.java, src/main/java/nl/haarlem/translations/zdstozgw/requesthandler/impl/logging/ZgwRequestResponseCycle.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsEdcLv01.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsParameters.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsParametersMetSortering.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsZakLv01.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java
xml-schema-compliance
better replication testing
=> xml-schema-compliance and better replication testing

src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java
=> Only add adres when a bag aoa.identification is specified for a person, closes #55

src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java
=> 87 Resultaat cannot be set from createzaak

src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zgw/client/ZGWClient.java
=> 92 Exception while setting 2 times the resultaattype, this should be a warning

docker_push.sh
=> Change docker hub repository and use git tag for image tag

src/main/java/nl/haarlem/translations/zdstozgw/config/ModelMapperConfig.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/Replicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/translate/GeefLijstZaakdocumentenTranslator.java, src/main/java/nl/haarlem/translations/zdstozgw/requesthandler/impl/logging/LoggingRequestInterceptor.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zgw/client/ZGWClient.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zgw/model/ZgwResultaat.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zgw/model/ZgwRol.java, src/test/resources/ladybug/01 Translate genereerZaakIdentificatie_Di02.report.xml, src/test/resources/ladybug/02 Translate creeerZaak_Lk01.report.xml, src/test/resources/ladybug/03 Translate updateZaak_Lk01.report.xml, src/test/resources/ladybug/04 Translate genereerDocumentIdentificatie_Di02.report.xml, src/test/resources/ladybug/05 Translate voegZaakdocumentToe_Lk01.report.xml, src/test/resources/ladybug/06 Translate updateZaak_Lk01 (A Verantwoordelijke).report.xml, src/test/resources/ladybug/06 Translate updateZaak_Lk01 (B).report.xml, src/test/resources/ladybug/07 Translate geefLijstZaakdocumenten_Lv01.report.xml, src/test/resources/ladybug/08 Translate geefZaakdocumentLezen_Lv01.report.xml, src/test/resources/ladybug/09 Translate updateZaak_Lk01.report.xml, src/test/resources/ladybug/10 Translate actualiseerZaakstatus_Lk01.report.xml, src/test/resources/ladybug/11 Translate geefZaakdetails_Lv01.report.xml
- Make Open Zaakbrug working with midoffice-vuller
- Better descriptions in the relations
- Removed replication errors
=> Burgerzaken

src/main/java/nl/haarlem/translations/zdstozgw/converter/ConverterFactory.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/ActualiseerZaakStatusReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/GeefLijstZaakdocumentenReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/GeefZaakdocumentLezenReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/Replicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/VoegZaakdocumentToeReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zgw/client/ZGWClient.java
Tested on basic workings with backoffice product and the existing zaaksysteem, will need some more fine tuning, but basic workings seem to be okay.
=> general functionalities of replication should work

src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java, src/main/resources/config.json_example
vergunningen backoffice application seems to work
=> Vergunningen

src/main/java/nl/haarlem/translations/zdstozgw/config/ModelMapperConfig.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java
- set einddatum in correct format to the laststatus
- refactored ModelMapperConfig to get access to the required functions
closes #135
=> Closes #135 : einddatum is always today

src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/ActualiseerZaakStatusReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/CreeerZaakReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/GeefLijstZaakdocumentenReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/GeefZaakDetailsReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/GeefZaakdocumentLezenReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/Replicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/UpdateZaakReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/VoegZaakdocumentToeReplicator.java
More defensive programmed, so there will be less impact on continuity
=> Multiple replication improvements

src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/Replicator.java
Keep running upon inconsistencies in the database/filestorage
Closes #146
=> Make sure that the synchronization keeps running, also with exceptions on fileread

commonground/checklist.md, src/main/java/nl/haarlem/translations/zdstozgw/translation/zgw/client/ZGWClient.java
=> Added the commonground checklist

src/main/java/nl/haarlem/translations/zdstozgw/requesthandler/impl/logging/ZdsRequestResponseCycle.java, src/main/java/nl/haarlem/translations/zdstozgw/requesthandler/impl/logging/ZgwRequestResponseCycle.java
=> added default constructors

src/main/java/nl/haarlem/translations/zdstozgw/config/ModelMapperConfig.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsGerelateerde.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsNietNatuurlijkPersoon.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zgw/model/ZgwBetrokkeneIdentificatie.java
=> Added (minimal) support for NietNatuurlijkPersoon

src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java, src/main/resources/application.properties_example
- support for multiple status
- cleaned/refactored code
- removed the zdstozgw.auto.laststatus parameter (obsolete)
- einddatum is now also provided from time, if it was today
Closes #163
=> Optimized status/resultaat logica

src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsAdres.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsNietNatuurlijkPersoon.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java, src/test/resources/ladybug/Suites4SociaalDomein 02 Translate creeerZaak_Lk01.report.xml
- more bedrijven fields
- default value of 'overig_privaatrechtelijke_rechtspersoon' when no other rechtsvorm could be resolved
Closes #185
=> Meer NNP ondersteuning

examples/nginx/openzaakbrug.conf
=> Add an example nginx configuration

src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsGerelateerde.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zgw/model/ZgwBetrokkeneIdentificatie.java
=> Support for vestigingen

src/main/java/nl/haarlem/translations/zdstozgw/converter/ConverterException.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zgw/client/ZGWClient.java, src/main/java/nl/haarlem/translations/zdstozgw/utils/XmlUtils.java, src/test/resources/ladybug/ErrorHandling 03 Invalid xml.report.xml, src/test/resources/ladybug/Suites4SociaalDomein 14 Translate updateZaak_Lk01.report.xml
Remove the leading: ﻿<?xml version="1.0" encoding="utf-8"?> if there is
Also added test-cases and make the code easier to debug
=> Added support for KANA 

docs/LadybugTests.md, src/test/resources/ladybug/ErrorHandling 03 Invalid xml.report.xml, src/test/resources/ladybug/Suites4SociaalDomein 14 Translate updateZaak_Lk01.report.xml
=> Fix ladybug errors

src/main/java/nl/haarlem/translations/zdstozgw/debug/Debugger.java, src/test/resources/ladybug/ErrorHandling 03 Invalid xml.report.xml
=> Make adding endpoint to testtool conditional

src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zgw/client/ZGWClient.java
also documenttype is now case insensitive
=> fixes: #242 Parent/child zaken are connected as child/parent

src/main/java/nl/haarlem/translations/zdstozgw/controller/SoapController.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/ConverterException.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/ActualiseerZaakStatusReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/CancelCheckoutReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/CreeerZaakReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/GeefLijstZaakdocumentenReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/GeefZaakDetailsReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/GeefZaakdocumentBewerkenReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/GeefZaakdocumentLezenReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/Replicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/UpdateZaakReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/UpdateZaakdocumentReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/VoegZaakdocumentToeReplicator.java, src/main/java/nl/haarlem/translations/zdstozgw/debug/Debugger.java, src/test/java/nl/haarlem/translations/zdstozgw/LadybugTests.java, src/test/resources/ladybug/ErrorHandling 05 Invalid SoapAction geefZaakdetails_Lv01(ABCDE).report.xml, src/test/resources/ladybug/ErrorHandling 06 Invalid SoapAction geefZaakdetails_Lv01(NULL).report.xml
Responses that were not http-status-ok throw now an ConverterException (we want to know the errors)
Closes #246
=> Replication errors

src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/Replicator.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java, src/main/resources/templates/error.html, src/main/resources/templates/index.html
=> Aantal prio issues

src/main/java/nl/haarlem/translations/zdstozgw/converter/impl/replicate/Replicator.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsVan.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsZaak.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java, src/main/resources/data.sql, src/test/resources/ladybug/Suites4SociaalDomein 02 Translate creeerZaak_Lk01.report.xml, src/test/resources/ladybug/Suites4SociaalDomein 08 Translate updateZaak_Lk01.report.xml, src/test/resources/ladybug/Suites4SociaalDomein 09 Translate updateZaak_Lk01.report.xml, src/test/resources/ladybug/Suites4SociaalDomein 12 Translate updateZaak_Lk01.report.xml, src/test/resources/ladybug/Suites4SociaalDomein 13 Translate actualiseerZaakstatus_Lk01.report.xml, src/test/resources/ladybug/Suites4SociaalDomein 14 Translate updateZaak_Lk01.report.xml
when verlenging.reden == null ==> setting the newvalue to null
=> Improve replication

src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java
=> replication: bugfix

src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/Endpoint.java, src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/model/ZdsStuurgegevens.java
fixed SoapUI tests (still 1 not working, but it seems that they should work)
=> fixed SoapUI tests (still 1 not working, but it seems that they should work)

pom.xml
Increment version & restore '-SNAPSHOT'
=> Increment-version-after-release-x.y.z
